trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node version 14.17.6'
  inputs:
    versionSpec: 14.17.6

- bash: yarn install --frozen-lockfile
  displayName: 'Install dependencies'

- bash: yarn lint
  displayName: 'Lint code'

- bash: yarn build
  displayName: 'Build'

- bash: yarn test:unit:ci
  displayName: 'Run tests'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
