trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: yarn install --frozen-lockfile
  displayName: 'Install dependencies'
- script: yarn lint
  displayName: 'Lint code'
- script: yarn build
  displayName: 'Build'
- script: yarn test:unit:ci
  displayName: 'Run tests'
